

CREATE TABLE REGION 
(
	REGION_NAME VARCHAR(5) NOT NULL PRIMARY KEY
	CHECK(REGION_NAME IN ('EAST','WEST','NORTH','SOUTH'))
);


CREATE TABLE BRANCH_DETAILS 
(
	BRANCH_ID VARCHAR(2) PRIMARY KEY,
    BRANCH_NAME VARCHAR(20) NOT NULL,
	BRANCH_TYPE VARCHAR(7) NOT NULL CHECK (BRANCH_TYPE IN ('SALES','SERVICE')),
	REGION VARCHAR(5) NOT NULL CHECK(REGION IN ('EAST','WEST','NORTH','SOUTH')),
	FOREIGN KEY (REGION) REFERENCES REGION(REGION_NAME)
);



CREATE TABLE CAR_DETAILS
(
	MODEL_NUM VARCHAR(10) PRIMARY KEY,
	MODEL_NAME VARCHAR(10),
	TYPE_OF_VEHICLE VARCHAR(3) CHECK (TYPE_OF_VEHICLE IN('HB','S','SUV')),
	VARIANT VARCHAR(7) CHECK (VARIANT IN('BASE','PREMIUM','TOP'))
);


CREATE TABLE CUSTOMER_DETAILS
(
	CUST_ID INT PRIMARY KEY,
    CUST_NAME VARCHAR(30) NOT NULL,
	DL_NUM VARCHAR(10) NOT NULL,
    GENDER VARCHAR(6) NOT NULL CHECK(GENDER IN ('MALE', 'FEMALE', 'OTHERS')),
    PHONE_NUM BIGINT,
    ADDRESS_RGN VARCHAR(5) NOT NULL CHECK(ADDRESS_RGN IN ('EAST','WEST','NORTH','SOUTH')),
    FOREIGN KEY (ADDRESS_RGN) REFERENCES REGION(REGION_NAME)
);

CREATE TABLE SALES_DATA
(
	SALE_ID INT PRIMARY KEY AUTO_INCREMENT,
	BRANCH_ID VARCHAR(2) NOT NULL,
	CUSTOMER_ID INT NOT NULL,
	CAR_MODEL VARCHAR(10) NOT NULL,
	SALE_DATE DATE NOT NULL,
    NUM_PLATE VARCHAR(10),
	FOREIGN KEY (BRANCH_ID) REFERENCES BRANCH_DETAILS(BRANCH_ID),
	FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER_DETAILS(CUST_ID),
	FOREIGN KEY (CAR_MODEL) REFERENCES CAR_DETAILS(MODEL_NUM)
);

CREATE TABLE SERVICE_DATA
(
	SERVICE_ID INT PRIMARY KEY AUTO_INCREMENT,
	BRANCH_ID VARCHAR(2) NOT NULL,
	SERVICE_DATE DATE,
    CUSTOMER_ID INT NOT NULL,
	SALE_ID INT NOT NULL,
    SERVICE_TYPE VARCHAR(8) NOT NULL CHECK(SERVICE_TYPE IN ('FIRST','SECOND','THIRD')),
	FOREIGN KEY (BRANCH_ID) REFERENCES BRANCH_DETAILS(BRANCH_ID),
	FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER_DETAILS(CUST_ID),
    FOREIGN KEY (SALE_ID) REFERENCES SALES_DATA(SALE_ID)
);
use tata_motors;
SELECT * FROM branch_details;
SELECT * FROM car_details;
SELECT * FROM customer_details;
SELECT * FROM region;
SELECT * FROM sales_data;
SELECT * FROM service_data;

